// data.js
const surahData = [
    { no: 1, nomAr: "الفاتحة", nomFr: "Al-Fatiha (L'Ouverture)", versets: 7, lieu: "Mecque", theme: "Essence du Coran", points: "Prière, louange et guidance." },
    { no: 2, nomAr: "البقرة", nomFr: "Al-Baqarah (La Vache)", versets: 286, lieu: "Médine", theme: "Législation et Foi", points: "Plus longue sourate, lois sociales, histoire d'Adam et Moïse." },
    { no: 3, nomAr: "آل عمران", nomFr: "Al-Imran (La Famille d'Imran)", versets: 200, lieu: "Médine", theme: "Unicité et Famille", points: "Naissance de Marie et Jésus, bataille d'Uhud." },
    { no: 4, nomAr: "النساء", nomFr: "An-Nisa (Les Femmes)", versets: 176, lieu: "Médine", theme: "Droits Sociaux", points: "Héritage, droits des femmes et des orphelins." },
    { no: 5, nomAr: "المائدة", nomFr: "Al-Ma'idah (La Table Servie)", versets: 120, lieu: "Médine", theme: "Contrats et Lois", points: "Dernières prescriptions alimentaires et rituelles." },
    { no: 6, nomAr: "الأنعام", nomFr: "Al-An'am (Les Bestiaux)", versets: 165, lieu: "Mecque", theme: "Monothéisme", points: "Preuves de l'existence de Dieu dans la création." },
    { no: 7, nomAr: "الأعراف", nomFr: "Al-A'raf (Les Murailles)", versets: 206, lieu: "Mecque", theme: "Destinée Humaine", points: "Lutte entre le bien et le mal, récits des prophètes." },
    { no: 8, nomAr: "الأنفال", nomFr: "Al-Anfal (Le Butin)", versets: 75, lieu: "Médine", theme: "Éthique de Guerre", points: "Bataille de Badr, confiance en Dieu." },
    { no: 9, nomAr: "التوبة", nomFr: "At-Tawbah (Le Désaveu)", versets: 129, lieu: "Médine", theme: "Repentance", points: "Seule sourate sans 'Bismillah' au début." },
    { no: 10, nomAr: "يونس", nomFr: "Yunus (Jonas)", versets: 109, lieu: "Mecque", theme: "Prophétie", points: "La patience face à l'incrédulité." },
    { no: 11, nomAr: "هود", nomFr: "Hud", versets: 123, lieu: "Mecque", theme: "Histoires des Prophètes", points: "Avertissement aux peuples injustes." },
    { no: 12, nomAr: "يوسف", nomFr: "Yusuf (Joseph)", versets: 111, lieu: "Mecque", theme: "L'épreuve et le succès", points: "Récit complet de la vie de Joseph." },
    { no: 13, nomAr: "الرعد", nomFr: "Ar-Ra'd (Le Tonnerre)", versets: 43, lieu: "Médine", theme: "Signes de Dieu", points: "La vérité triomphe de l'erreur." },
    { no: 14, nomAr: "إبراهيم", nomFr: "Ibrahim (Abraham)", versets: 52, lieu: "Mecque", theme: "Lumière vs Ténèbres", points: "La prière d'Abraham pour sa descendance." },
    { no: 15, nomAr: "الحجر", nomFr: "Al-Hijr", versets: 99, lieu: "Mecque", theme: "Protection Divine", points: "Dieu préserve Son message." },
    { no: 16, nomAr: "النحل", nomFr: "An-Nahl (Les Abeilles)", versets: 128, lieu: "Mecque", theme: "Bienfaits Divins", points: "La sagesse dans la nature." },
    { no: 17, nomAr: "الإسراء", nomFr: "Al-Isra (Le Voyage Nocturne)", versets: 111, lieu: "Mecque", theme: "Spiritualité", points: "Le voyage du Prophète à Jérusalem." },
    { no: 18, nomAr: "الكهف", nomFr: "Al-Kahf (La Caverne)", versets: 110, lieu: "Mecque", theme: "Épreuves de la Foi", points: "Gens de la caverne, Moïse et Khidr." },
    { no: 19, nomAr: "مريم", nomFr: "Maryam (Marie)", versets: 98, lieu: "Mecque", theme: "Miséricorde", points: "Histoires de Zacharie, Jean et Marie." },
    { no: 20, nomAr: "طه", nomFr: "Ta-Ha", versets: 135, lieu: "Mecque", theme: "Appel de Moïse", points: "Réconfort pour le Prophète." },
    { no: 21, nomAr: "الأنبياء", nomFr: "Al-Anbiya (Les Prophètes)", versets: 112, lieu: "Mecque", theme: "Unité du Message", points: "Les prophètes sont une seule communauté." },
    { no: 22, nomAr: "الحج", nomFr: "Al-Hajj (Le Pèlerinage)", versets: 78, lieu: "Médine", theme: "Adoration", points: "Le sens du pèlerinage et le Jour Dernier." },
    { no: 23, nomAr: "المؤمنون", nomFr: "Al-Mu'minun (Les Croyants)", versets: 118, lieu: "Mecque", theme: "Qualités de la Foi", points: "Le succès véritable des croyants." },
    { no: 24, nomAr: "النور", nomFr: "An-Nur (La Lumière)", versets: 64, lieu: "Médine", theme: "Morale Sociale", points: "Lois sur la pudeur et la vie privée." },
    { no: 25, nomAr: "الفرقان", nomFr: "Al-Furqan (Le Discernement)", versets: 77, lieu: "Mecque", theme: "Critère du Bien", points: "Le Coran comme guide." },
    { no: 26, nomAr: "الشعراء", nomFr: "Ash-Shu'ara (Les Poètes)", versets: 227, lieu: "Mecque", theme: "Communication", points: "L'éloquence du message divin." },
    { no: 27, nomAr: "النمل", nomFr: "An-Naml (Les Fourmis)", versets: 93, lieu: "Mecque", theme: "Savoir et Pouvoir", points: "Salomon et la reine de Saba." },
    { no: 28, nomAr: "القصص", nomFr: "Al-Qasas (Le Récit)", versets: 88, lieu: "Mecque", theme: "Victoire des Faibles", points: "Enfance de Moïse et chute de Pharaon." },
    { no: 29, nomAr: "العنكبوت", nomFr: "Al-Ankabut (L'Araignée)", versets: 69, lieu: "Mecque", theme: "Épreuve", points: "La fragilité des fausses croyances." },
    { no: 30, nomAr: "الروم", nomFr: "Ar-Rum (Les Romains)", versets: 60, lieu: "Mecque", theme: "Signes Historiques", points: "Prédiction de la victoire byzantine." },
	{ no: 31, nomAr: "لقمان", nomFr: "Luqman", versets: 34, lieu: "Mecque", theme: "Sagesse paternelle", points: "Conseils de Luqman à son fils sur l'unicité et l'humilité." },
    { no: 32, nomAr: "السجدة", nomFr: "As-Sajdah (La Prosternation)", versets: 30, lieu: "Mecque", theme: "Création et Foi", points: "La création de l'homme et la certitude de la rencontre avec Dieu." },
    { no: 33, nomAr: "الأحزاب", nomFr: "Al-Ahzab (Les Coalisés)", versets: 73, lieu: "Médine", theme: "Vie sociale et Prophète", points: "Bataille du Fossé et règles sur la vie privée du Prophète." },
    { no: 34, nomAr: "سبأ", nomFr: "Saba", versets: 54, lieu: "Mecque", theme: "Gratitude et Pouvoir", points: "Histoires de David, Salomon et la chute du peuple de Saba." },
    { no: 35, nomAr: "فاطر", nomFr: "Fatir (Le Créateur)", versets: 45, lieu: "Mecque", theme: "Puissance divine", points: "Dieu comme créateur des cieux, de la terre et des anges." },
    { no: 36, nomAr: "يس", nomFr: "Ya-Sin", versets: 83, lieu: "Mecque", theme: "Cœur du Coran", points: "Preuves de la résurrection et messagerie des prophètes." },
    { no: 37, nomAr: "الصافات", nomFr: "As-Saffat (Les Rangés)", versets: 182, lieu: "Mecque", theme: "Unicité absolue", points: "Les anges en rangs et le sacrifice d'Ismaël par Abraham." },
    { no: 38, nomAr: "ص", nomFr: "Sad", versets: 88, lieu: "Mecque", theme: "Patience des prophètes", points: "Épreuves de David, Salomon et Job (Ayoub)." },
    { no: 39, nomAr: "الزمر", nomFr: "Az-Zumar (Les Groupes)", versets: 75, lieu: "Mecque", theme: "Sincérité (Ikhlas)", points: "L'entrée des croyants et des mécréants au Paradis/Enfer par groupes." },
    { no: 40, nomAr: "غافر", nomFr: "Ghafir (Le Pardonneur)", versets: 85, lieu: "Mecque", theme: "Pardon et Appel", points: "Le croyant de la famille de Pharaon qui cache sa foi." },
    { no: 41, nomAr: "فصلت", nomFr: "Fussilat (Les versets détaillés)", versets: 54, lieu: "Mecque", theme: "Clarté du message", points: "Les éléments de la nature comme signes de la puissance divine." },
    { no: 42, nomAr: "الشورى", nomFr: "Ash-Shura (La Consultation)", versets: 53, lieu: "Mecque", theme: "Gouvernance et Unité", points: "Le principe de la Choura (consultation) entre les croyants." },
    { no: 43, nomAr: "الزخرف", nomFr: "Az-Zukhruf (L'Ornement)", versets: 89, lieu: "Mecque", theme: "Valeurs spirituelles", points: "Critique de l'attachement excessif aux richesses de ce monde." },
    { no: 44, nomAr: "الدخان", nomFr: "Ad-Dukhan (La Fumée)", versets: 59, lieu: "Mecque", theme: "Avertissement", points: "Mention de la Nuit du Destin et de la fumée de la fin des temps." },
    { no: 45, nomAr: "الجاثية", nomFr: "Al-Jathiyah (L'Agenouillée)", versets: 37, lieu: "Mecque", theme: "Justice finale", points: "L'humanité agenouillée devant son Seigneur au Jour du Jugement." },
    { no: 46, nomAr: "الأحقاف", nomFr: "Al-Ahqaf", versets: 35, lieu: "Mecque", theme: "Responsabilité", points: "Le peuple des 'Ad et l'importance du respect envers les parents." },
    { no: 47, nomAr: "محمد", nomFr: "Muhammad", versets: 38, lieu: "Médine", theme: "Combat et Fermeté", points: "Directives sur le combat et la promesse du Paradis." },
    { no: 48, nomAr: "الفتح", nomFr: "Al-Fath (La Victoire éclatante)", versets: 29, lieu: "Médine", theme: "Paix et Succès", points: "Le traité d'Hudaibiyah et la vision de la conquête de la Mecque." },
    { no: 49, nomAr: "الحجرات", nomFr: "Al-Hujurat (Les Appartements)", versets: 18, lieu: "Médine", theme: "Éthique sociale", points: "Règles sur la médisance, la suspicion et la fraternité humaine." },
    { no: 50, nomAr: "ق", nomFr: "Qaf", versets: 45, lieu: "Mecque", theme: "Rappel de la mort", points: "La résurrection et l'enregistrement des actes par les anges." },
    { no: 51, nomAr: "الذاريات", nomFr: "Adh-Dhariyat", versets: 60, lieu: "Mecque", theme: "Subsistance", points: "Le but de la création des djinns et des hommes : l'adoration." },
    { no: 52, nomAr: "الطور", nomFr: "At-Tur (Le Mont)", versets: 49, lieu: "Mecque", theme: "Récompense divine", points: "Description détaillée des délices promis aux pieux au Paradis." },
    { no: 53, nomAr: "النجم", nomFr: "An-Najm (L'Étoile)", versets: 62, lieu: "Mecque", theme: "Révélation", points: "Le Prophète au 'Lotus de la Limite' lors de l'ascension nocturne." },
    { no: 54, nomAr: "القمر", nomFr: "Al-Qamar (La Lune)", versets: 55, lieu: "Mecque", theme: "Signes et Miracles", points: "Le miracle de la lune fendue et le rappel des peuples passés." },
    { no: 55, nomAr: "الرحمن", nomFr: "Ar-Rahman (Le Tout Miséricordieux)", versets: 78, lieu: "Médine", theme: "Bienfaits divins", points: "Description poétique des deux mondes et de la miséricorde de Dieu." },
    { no: 56, nomAr: "الواقعة", nomFr: "Al-Waqi'ah (L'Événement)", versets: 96, lieu: "Mecque", theme: "Destinée finale", points: "La division des hommes en trois catégories au Jour Dernier." },
    { no: 57, nomAr: "الحديد", nomFr: "Al-Hadid (Le Fer)", versets: 29, lieu: "Médine", theme: "Foi et Sacrifice", points: "L'importance de l'aumône et la puissance du fer comme signe." },
    { no: 58, nomAr: "المجادلة", nomFr: "Al-Mujadila (La Discussion)", versets: 22, lieu: "Médine", theme: "Droit des femmes", points: "La femme qui plaidait son cas auprès du Prophète." },
    { no: 59, nomAr: "الحشر", nomFr: "Al-Hashr (L'Exode)", versets: 24, lieu: "Médine", theme: "Expatriation et Unité", points: "L'exil de la tribu des Banu Nadir et les noms parfaits de Dieu." },
    { no: 60, nomAr: "الممتحنة", nomFr: "Al-Mumtahanah", versets: 13, lieu: "Médine", theme: "Loyauté", points: "L'examen de foi des femmes immigrées à Médine." },
	{ no: 61, nomAr: "الصف", nomFr: "As-Saff (Le Rang)", versets: 14, lieu: "Médine", theme: "Unité et Discipline", points: "Appel à la cohérence entre les paroles et les actes des croyants." },
    { no: 62, nomAr: "الجمعة", nomFr: "Al-Jumu'ah (Le Vendredi)", versets: 11, lieu: "Médine", theme: "L'Appel à la prière", points: "Importance de la prière collective du vendredi et le commerce." },
    { no: 63, nomAr: "المنافقون", nomFr: "Al-Munafiqun (Les Hypocrites)", versets: 11, lieu: "Médine", theme: "Sincérité", points: "Description des traits de caractère des hypocrites à Médine." },
    { no: 64, nomAr: "التغابن", nomFr: "At-Taghabun (La Grande Perte)", versets: 18, lieu: "Médine", theme: "Destinée et Foi", points: "Le jour où les gains et pertes réels seront révélés." },
    { no: 65, nomAr: "الطلاق", nomFr: "At-Talaq (Le Divorce)", versets: 12, lieu: "Médine", theme: "Lois sociales", points: "Règles éthiques et procédures à suivre en cas de divorce." },
    { no: 66, nomAr: "التحريم", nomFr: "At-Tahrim (L'Interdiction)", versets: 12, lieu: "Médine", theme: "Vie familiale", points: "Leçons tirées de la vie domestique du Prophète." },
    { no: 67, nomAr: "الملك", nomFr: "Al-Mulk (La Royauté)", versets: 30, lieu: "Mecque", theme: "Souveraineté Divine", points: "La perfection de la création et la protection contre le châtiment." },
    { no: 68, nomAr: "القلم", nomFr: "Al-Qalam (La Plume)", versets: 52, lieu: "Mecque", theme: "Éthique et Plume", points: "Défense du caractère du Prophète et l'importance du savoir." },
    { no: 69, nomAr: "الحاقة", nomFr: "Al-Haqqah (Celle qui montre la vérité)", versets: 52, lieu: "Mecque", theme: "Réalité Inévitable", points: "La certitude du Jour du Jugement et le sort des peuples anciens." },
    { no: 70, nomAr: "المعارج", nomFr: "Al-Ma'arij (Les Voies d'ascension)", versets: 44, lieu: "Mecque", theme: "Patience et Prière", points: "La nature humaine face à l'épreuve et les niveaux spirituels." },
    { no: 71, nomAr: "نوح", nomFr: "Nuh (Noé)", versets: 28, lieu: "Mecque", theme: "Appel Prophétique", points: "Le récit de la prédication constante de Noé envers son peuple." },
    { no: 72, nomAr: "الجن", nomFr: "Al-Jinn (Les Djinns)", versets: 28, lieu: "Mecque", theme: "Le Monde Invisible", points: "Le récit des djinns qui ont écouté et accepté le Coran." },
    { no: 73, nomAr: "المزمل", nomFr: "Al-Muzzammil (L'Enveloppé)", versets: 20, lieu: "Mecque", theme: "Prière Nocturne", points: "Préparation spirituelle du Prophète par la prière de nuit." },
    { no: 74, nomAr: "المدثر", nomFr: "Al-Muddathir (Le Revêtu d'un manteau)", versets: 56, lieu: "Mecque", theme: "Avertissement Public", points: "L'ordre de se lever et d'avertir les gens ouvertement." },
    { no: 75, nomAr: "القيامة", nomFr: "Al-Qiyamah (La Résurrection)", versets: 40, lieu: "Mecque", theme: "Fin des Temps", points: "Description du moment où l'âme quitte le corps et la résurrection." },
    { no: 76, nomAr: "الإنسان", nomFr: "Al-Insan (L'Homme)", versets: 31, lieu: "Médine", theme: "Générosité", points: "La création de l'homme et les délices du Paradis pour les généreux." },
    { no: 77, nomAr: "المرسلات", nomFr: "Al-Mursalat (Les Envoyés)", versets: 50, lieu: "Mecque", theme: "Vérité Indéniable", points: "Refrain : 'Malheur, ce jour-là, à ceux qui criaient au mensonge'." },
    { no: 78, nomAr: "النبأ", nomFr: "An-Naba (La Nouvelle)", versets: 40, lieu: "Mecque", theme: "Le Jour de la Décision", points: "Les signes de la nature et la réalité du jugement dernier." },
    { no: 79, nomAr: "النازعات", nomFr: "An-Nazi'at (Les Anges qui arrachent)", versets: 46, lieu: "Mecque", theme: "Transition de l'Âme", points: "Les anges chargés de la mort et le rappel de Moïse." },
    { no: 80, nomAr: "عبس", nomFr: "Abasa (Il s'est renfrogné)", versets: 42, lieu: "Mecque", theme: "Égalité devant Dieu", points: "Réprimande divine au Prophète concernant l'aveugle Ibn Umm Maktum." },
    { no: 81, nomAr: "التكوير", nomFr: "At-Takwir (L'Obscurcissement)", versets: 29, lieu: "Mecque", theme: "Bouleversement Cosmique", points: "Les signes cosmiques marquant la fin du monde." },
    { no: 82, nomAr: "الانفطار", nomFr: "Al-Infitar (La Rupture)", versets: 19, lieu: "Mecque", theme: "Fragilité", points: "Le ciel qui se fend et l'enregistrement fidèle des actes." },
    { no: 83, nomAr: "المطففين", nomFr: "Al-Mutaffifin (Les Fraudeurs)", versets: 36, lieu: "Mecque", theme: "Justice Économique", points: "Dénonciation de la fraude dans les mesures et les poids." },
    { no: 84, nomAr: "الانشقاق", nomFr: "Al-Inshiqaq (La Déchirure)", versets: 25, lieu: "Mecque", theme: "Redition de comptes", points: "Le moment où chacun recevra son registre d'actes." },
    { no: 85, nomAr: "البروج", nomFr: "Al-Buruj (Les Constellations)", versets: 22, lieu: "Mecque", theme: "Persécution et Foi", points: "L'histoire des 'Gens du Fossé' sacrifiés pour leur foi." },
    { no: 86, nomAr: "الطارق", nomFr: "At-Tariq (L'Astre Nocturne)", versets: 17, lieu: "Mecque", theme: "Protection Divine", points: "Chaque âme a un gardien et la réflexion sur l'origine humaine." },
    { no: 87, nomAr: "الأعلى", nomFr: "Al-A'la (Le Très-Haut)", versets: 19, lieu: "Mecque", theme: "Glorification", points: "L'éminence de Dieu et le rappel des Feuillets d'Abraham et Moïse." },
    { no: 88, nomAr: "الغاشية", nomFr: "Al-Ghashiyah (L'Enveloppante)", versets: 26, lieu: "Mecque", theme: "Double Destin", points: "Description des visages humiliés et des visages rayonnants." },
    { no: 89, nomAr: "الفجر", nomFr: "Al-Fajr (L'Aube)", versets: 30, lieu: "Mecque", theme: "Épreuve du Pouvoir", points: "Rappel des peuples de 'Ad et Thamud et l'âme apaisée." },
    { no: 90, nomAr: "البلد", nomFr: "Al-Balad (La Cité)", versets: 20, lieu: "Mecque", theme: "La Voie Difficile", points: "La lutte humaine et le choix entre la voie de la vertu ou du mal." },
	{ no: 91, nomAr: "الشمس", nomFr: "Ash-Shams (Le Soleil)", versets: 15, lieu: "Mecque", theme: "Pureté de l'âme", points: "Série de serments cosmiques sur le succès de l'âme purifiée." },
    { no: 92, nomAr: "الليل", nomFr: "Al-Layl (La Nuit)", versets: 21, lieu: "Mecque", theme: "Diversité des efforts", points: "Le contraste entre la générosité et l'avarice." },
    { no: 93, nomAr: "الضحى", nomFr: "Ad-Duha (Le Jour Montant)", versets: 11, lieu: "Mecque", theme: "Réconfort", points: "Message d'espoir au Prophète : 'Ton Seigneur ne t'a ni abandonné, ni détesté'." },
    { no: 94, nomAr: "الشرح", nomFr: "Ash-Sharh (L'Ouverture)", versets: 8, lieu: "Mecque", theme: "Soulagement", points: "L'apaisement du cœur : 'A côté de la difficulté est, certes, une facilité'." },
    { no: 95, nomAr: "التين", nomFr: "At-Tin (Le Figuier)", versets: 8, lieu: "Mecque", theme: "Nature humaine", points: "L'homme créé dans la forme la plus parfaite." },
    { no: 96, nomAr: "العلق", nomFr: "Al-Alaq (L'Adhérence)", versets: 19, lieu: "Mecque", theme: "Savoir", points: "Contient les 5 premiers versets révélés : 'Lis ! au nom de ton Seigneur'." },
    { no: 97, nomAr: "القدر", nomFr: "Al-Qadr (La Destinée)", versets: 5, lieu: "Mecque", theme: "Nuit Sacrée", points: "Célébration de la nuit de la révélation, meilleure que mille mois." },
    { no: 98, nomAr: "البينة", nomFr: "Al-Bayyinah (La Preuve)", versets: 8, lieu: "Médine", theme: "Clarté", points: "Le rôle du Messager et du Livre comme preuves claires." },
    { no: 99, nomAr: "الزلزلة", nomFr: "Az-Zalzalah (Le Tremblement de terre)", versets: 8, lieu: "Médine", theme: "Justice absolue", points: "La terre témoignera de chaque atome de bien ou de mal." },
    { no: 100, nomAr: "العاديات", nomFr: "Al-Adiyat (Les Coursiers)", versets: 11, lieu: "Mecque", theme: "Ingratitude", points: "L'impétuosité de l'homme et son amour pour les richesses." },
    { no: 101, nomAr: "القارعة", nomFr: "Al-Qari'ah (Le Fracas)", versets: 11, lieu: "Mecque", theme: "Le Jugement", points: "Le jour où les hommes seront comme des papillons éparpillés." },
    { no: 102, nomAr: "التكاثر", nomFr: "At-Takathur (La Course aux richesses)", versets: 8, lieu: "Mecque", theme: "Distraction", points: "La rivalité dans l'accumulation des biens jusqu'à la tombe." },
    { no: 103, nomAr: "العصر", nomFr: "Al-Asr (Le Temps)", versets: 3, lieu: "Mecque", theme: "Le Succès", points: "La formule du salut : foi, bonnes œuvres, vérité et patience." },
    { no: 104, nomAr: "الهمزة", nomFr: "Al-Humazah (Les Calomniateurs)", versets: 9, lieu: "Mecque", theme: "Éthique sociale", points: "Avertissement contre la médisance et l'arrogance de la fortune." },
    { no: 105, nomAr: "الفيل", nomFr: "Al-Fil (L'Éléphant)", versets: 5, lieu: "Mecque", theme: "Protection Divine", points: "Rappel de la défaite de l'armée d'Abraha devant la Mecque." },
    { no: 106, nomAr: "قريش", nomFr: "Quraish", versets: 4, lieu: "Mecque", theme: "Gratitude", points: "Appel aux Quraysh à adorer le Seigneur de la Kaaba." },
    { no: 107, nomAr: "الماعون", nomFr: "Al-Ma'un (L'Ustensile)", versets: 7, lieu: "Mecque", theme: "Solidarité", points: "Critique de la piété superficielle sans aide aux nécessiteux." },
    { no: 108, nomAr: "الكوثر", nomFr: "Al-Kawthar (L'Abondance)", versets: 3, lieu: "Mecque", theme: "Don Divin", points: "La plus courte sourate, consolation pour le Prophète." },
    { no: 109, nomAr: "الكافرون", nomFr: "Al-Kafirun (Les Discutants)", versets: 6, lieu: "Mecque", theme: "Liberté de foi", points: "Distinction claire entre les voies d'adoration." },
    { no: 110, nomAr: "النصر", nomFr: "An-Nasr (Le Secours)", versets: 3, lieu: "Médine", theme: "Victoire Finale", points: "Annonce de l'entrée massive des gens dans l'Islam." },
    { no: 111, nomAr: "المسد", nomFr: "Al-Masad (Les Fibres)", versets: 5, lieu: "Mecque", theme: "Justice", points: "Le sort d'Abu Lahab, opposant acharné au message." },
    { no: 112, nomAr: "الإخلاص", nomFr: "Al-Ikhlas (Le Monothéisme pur)", versets: 4, lieu: "Mecque", theme: "Unicité (Tawhid)", points: "Définition concise de l'essence divine." },
    { no: 113, nomAr: "الفلق", nomFr: "Al-Falaq (L'Aube naissante)", versets: 5, lieu: "Mecque", theme: "Protection", points: "Refuge contre les maux extérieurs et l'envie." },
    { no: 114, nomAr: "الناس", nomFr: "An-Nas (Les Hommes)", versets: 6, lieu: "Mecque", theme: "Protection", points: "Refuge contre les suggestions internes (le Waswas)." }
];
